name: "Install kfp & kfp-kubernetes"
description: "Install kfp & kfp-kubernetes"
inputs:
  build_version:
    required: true
    default: "1.3.0"
    description: "build package version"
  generate_golang_proto:
    required: true
    default: "false"
    description: "optionally generate golang proto files"
runs:
  using: "composite"
  steps:
    - name: Install build tool
      shell: bash
      run: |
        pip install --upgrade pip
        pip install build==${{inputs.build_version}}

    - name: Generate kfp-kubernetes python proto files
      shell: bash
      working-directory: ./kubernetes_platform
      run: make clean python

    - name: Generate kfp-kubernetes golang proto files
      shell: bash
      if: ${{ inputs.generate_golang_proto == 'true' }}
      working-directory: ./kubernetes_platform
      run: make golang

    - name: Build & install kfp from source
      id: install-kfp
      shell: bash
      working-directory: sdk/python
      run: |
        rm -rf dist/
        python -m build .
        pip install dist/*.whl